name: Super-Liner

on: push

jobs:
  super-lint:
    name: Lint code base
    run-on: ubuntu-lastest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Super-Linter
        uses: github/super-liner@v4
        env:
          DEFALULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
